# 6 `rampup-v1` Environment Check with SB3
Stable Baselines3 offers an [environment checker](https://stable-baselines3.readthedocs.io/en/master/common/env_checker.html?highlight=check_env) to test an environment for conformity with the Gym API. Warnings are returned if the environment does not conform.

In [1]:
import numpy as np
from plan_opt.demand import Demand
from plan_opt.envs.rampup1 import RampupEnv1
from stable_baselines3.common.env_checker import check_env

In [2]:
D = Demand(seed=3348)
D.generate_demand()
D.add_sudden_change()

In [3]:
env = RampupEnv1(demand=D)

In [4]:
a = env.observation_space.sample()
a

array([[[229, 205, 164],
        [  0,   0,   0],
        [  1,   0,   1],
        [  0,   1,   0],
        [  1,   0,   1]]], dtype=uint8)

In [5]:
a.shape

(1, 5, 3)

In [6]:
b = env.reset()
b

array([[[1, 1, 2],
        [0, 0, 0],
        [1, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]], dtype=uint8)

In [7]:
b.shape

(1, 5, 3)

In [8]:
len(env.obs_demand)

1098

In [9]:
np.set_printoptions(threshold=np.inf)
env.obs_demand

array([ 1,  0,  1,  2,  0,  2,  1,  0,  1,  1,  1,  1,  1,  2,  1,  1,  2,
        2,  1,  1,  2,  1,  1,  0,  1,  2,  1,  1,  1,  1,  1,  0,  1,  1,
        1,  1,  1,  2,  1,  1,  1,  2,  2,  1,  0,  0,  1,  1,  2,  1,  1,
        0,  1,  1,  1,  1,  2,  1,  1,  1,  2,  1,  1,  0,  1,  1,  1,  2,
        1,  2,  2,  2,  2,  1,  1,  2,  1,  1,  1,  2,  1,  1,  3,  2,  1,
        2,  2,  1,  2,  3,  6,  1,  2,  1,  2,  2,  1,  2,  2,  1,  1,  2,
        1,  2,  1,  1,  2,  2,  1,  1,  1,  1,  1,  1,  2,  1,  2,  1,  1,
        2,  2,  1,  1,  2,  2,  0,  2,  1,  2,  1,  2,  1,  1,  1,  1,  1,
        2,  1,  1,  2,  1,  2,  1,  3,  1,  1,  1,  2,  2,  1,  1,  2,  0,
        1,  1,  2,  1,  2,  2,  1,  1,  2,  2,  1,  2,  1,  1,  1,  1,  1,
        2,  2,  1,  1,  1,  1,  2,  2,  2,  1,  2,  1,  1,  1,  1,  2,  1,
        1,  2,  2,  1,  1,  2,  2,  2,  1,  1,  1,  1,  2,  1,  1,  1,  2,
        1,  2,  1,  2,  2,  1,  2,  2,  1,  1,  1,  1,  1,  2,  1,  1,  2,
        1,  2,  1,  2,  2

In [10]:
env.observation_space

Box(1, 5, 3)

In [11]:
check_env(env)

/Users/seppmacmini/opt/miniconda3/envs/rl/lib/python3.8/site-packages/stable_baselines3/common/env_checker.py:33: UserWarning: It seems that your observation space is an image but the upper and lower bounds are not in [0, 255]. Because the CNN policy normalize automatically the observation you may encounter issue if the values are not in that range.
  warnings.warn(
/Users/seppmacmini/opt/miniconda3/envs/rl/lib/python3.8/site-packages/stable_baselines3/common/env_checker.py:41: UserWarning: The minimal resolution for an image is 36x36 for the default CnnPolicy. You might need to use a custom `cnn_extractor` cf https://stable-baselines3.readthedocs.io/en/master/guide/custom_policy.html
  warnings.warn(
