# 4 Finding a suitable observation space

In [1]:
import numpy as np
from gym import spaces

Definition of observation space s1:

`gym.spaces.Box(<min of values>, <max of values>, [<fleet size>, <horizon (visible timeframe)>, <dimension of features>])`

In [2]:
s1 = spaces.Box(0, 1, [1, 28, 2])
print(s1)
s1.sample()

Box(1, 28, 2)


array([[[0.20499496, 0.7766323 ],
        [0.5486788 , 0.5718292 ],
        [0.51125413, 0.333279  ],
        [0.95969   , 0.90512764],
        [0.25948215, 0.54595804],
        [0.70270354, 0.52475715],
        [0.82416105, 0.28166088],
        [0.30247712, 0.55618787],
        [0.076651  , 0.83731365],
        [0.75352645, 0.7090701 ],
        [0.21626137, 0.04707464],
        [0.00665956, 0.3721909 ],
        [0.66595906, 0.86450195],
        [0.2912639 , 0.48786792],
        [0.72731024, 0.2787828 ],
        [0.9134719 , 0.2707627 ],
        [0.93073153, 0.90313756],
        [0.9982654 , 0.31188828],
        [0.93966985, 0.15153645],
        [0.6110561 , 0.73930115],
        [0.8217738 , 0.19068488],
        [0.9483006 , 0.9065174 ],
        [0.12468159, 0.88644356],
        [0.02492327, 0.77279776],
        [0.42595658, 0.95892495],
        [0.3358651 , 0.38771638],
        [0.69922   , 0.64078987],
        [0.40656406, 0.58355516]]], dtype=float32)

In [3]:
s2 = spaces.Tuple((spaces.Discrete(4), spaces.Box(0, 1, [28])))
print(s2)
s2.sample()

Tuple(Discrete(4), Box(28,))


(0,
 array([5.1690180e-02, 7.4636734e-01, 9.1547680e-01, 8.6549437e-01,
        1.9957392e-01, 7.3252589e-01, 9.1219485e-01, 4.7924969e-01,
        1.7571065e-01, 1.6625874e-01, 7.2721452e-01, 7.8783810e-01,
        8.3377182e-01, 2.6706600e-01, 8.4512764e-01, 7.2790438e-01,
        8.9058328e-01, 8.3763981e-01, 9.4753861e-01, 8.3634371e-01,
        3.0962491e-01, 3.7184235e-01, 7.0802671e-01, 4.9582168e-01,
        1.0580006e-01, 6.4465392e-01, 4.2459530e-01, 1.8628236e-04],
       dtype=float32))

In [4]:
s3 = spaces.Tuple((spaces.Discrete(4), spaces.Discrete(28), spaces.Box(0, 1, [28])))
print(s3)
s3.sample()

Tuple(Discrete(4), Discrete(28), Box(28,))


(3,
 18,
 array([0.8242329 , 0.96507376, 0.32726488, 0.59034956, 0.04922798,
        0.6804096 , 0.07127684, 0.1135989 , 0.906052  , 0.77609867,
        0.35471818, 0.11719381, 0.62109196, 0.45237312, 0.37309784,
        0.9302779 , 0.06319191, 0.48033848, 0.05680528, 0.94291985,
        0.537903  , 0.8278337 , 0.7556415 , 0.07752164, 0.9640734 ,
        0.82338154, 0.9227453 , 0.3560563 ], dtype=float32))

In [5]:
s4 = spaces.Box(0, 1, [1])
print(s4)
s4.sample()

Box(1,)


array([0.43078256], dtype=float32)

In [6]:
s5 = spaces.Box(low=np.array([0, 1, 2, 3, 4]), high=np.array([10, 20, 30, 40, 50]))
print(s5)
s5.sample()

Box(5,)


/Users/seppmacmini/opt/miniconda3/envs/rl/lib/python3.8/site-packages/gym/logger.py:30: UserWarning: WARN: Box bound precision lowered by casting to float32
  warnings.warn(colorize('%s: %s'%('WARN', msg % args), 'yellow'))


array([ 3.776801 ,  3.38608  , 17.448107 , 23.508696 ,  7.4256988],
      dtype=float32)

In [7]:
# 2 resources, 5 features (normalized demand and dummy encoded status), horizon of 28
s6 = spaces.Box(0, 1, [5, 2, 28], dtype=np.float32)
print(s6)
s6.sample()

Box(5, 2, 28)


array([[[0.5433515 , 0.8844221 , 0.99703515, 0.5992474 , 0.46297908,
         0.12968157, 0.38175654, 0.30048004, 0.25885862, 0.9865745 ,
         0.58790517, 0.7168101 , 0.68575156, 0.6774456 , 0.03486137,
         0.34208447, 0.79935277, 0.6753521 , 0.15990818, 0.02480768,
         0.448767  , 0.5946987 , 0.84546506, 0.874109  , 0.07599583,
         0.35225976, 0.46229893, 0.6497362 ],
        [0.888932  , 0.8975198 , 0.0108519 , 0.79080224, 0.89498657,
         0.75405586, 0.49196014, 0.7485023 , 0.21511135, 0.87938714,
         0.23616499, 0.7019275 , 0.33278272, 0.25274602, 0.2681342 ,
         0.4506528 , 0.6678427 , 0.8365866 , 0.8615918 , 0.8022297 ,
         0.41498637, 0.32410833, 0.33721864, 0.3785197 , 0.09787851,
         0.76185393, 0.29879543, 0.21301812]],

       [[0.8962152 , 0.7155707 , 0.94689703, 0.12447562, 0.91897666,
         0.98928523, 0.8210892 , 0.44903484, 0.9326475 , 0.43045455,
         0.8174986 , 0.46829343, 0.68125165, 0.675524  , 0.16484264,
         

In [8]:
# 2 resources, 5 features (normalized demand and dummy encoded status), horizon of 28
s7 = spaces.Box(0, 1, [2, 4, 28], dtype=np.float32)
print(s7)
s7.sample()

Box(2, 4, 28)


array([[[0.95162034, 0.21479918, 0.03935853, 0.37527296, 0.2706008 ,
         0.01778829, 0.43458238, 0.16809773, 0.7837156 , 0.5319445 ,
         0.65469253, 0.00189595, 0.92104554, 0.01581484, 0.5125212 ,
         0.4691027 , 0.2781975 , 0.7490448 , 0.7550369 , 0.57770807,
         0.4113676 , 0.58215344, 0.67581606, 0.81980145, 0.91831505,
         0.6149518 , 0.20761518, 0.05671289],
        [0.10860965, 0.2537258 , 0.85246533, 0.41862616, 0.6597186 ,
         0.5254356 , 0.99050045, 0.11568951, 0.5093163 , 0.5158921 ,
         0.46859115, 0.41586277, 0.1768847 , 0.020048  , 0.30735838,
         0.6029293 , 0.5064491 , 0.3011921 , 0.9905647 , 0.00326818,
         0.8210692 , 0.7027861 , 0.48910996, 0.19245605, 0.39955392,
         0.79648024, 0.69329566, 0.7614364 ],
        [0.8447765 , 0.78619564, 0.46097103, 0.5064403 , 0.4363197 ,
         0.8532769 , 0.09043366, 0.1773865 , 0.43279958, 0.41080445,
         0.75226694, 0.10894303, 0.6166486 , 0.4165069 , 0.58204466,
         0.

In [9]:
# 2 resources, 5 features (normalized demand and dummy encoded status), horizon of 28
s7 = spaces.Box(0, 1, [2, 4, 28], dtype=np.float32)
print(s7)
s7.sample()

Box(2, 4, 28)


array([[[6.80630188e-03, 3.09770823e-01, 3.22124988e-01, 3.14579338e-01,
         9.09673989e-01, 3.31552058e-01, 9.40291286e-01, 1.14103556e-01,
         9.50038970e-01, 9.56493735e-01, 5.30584216e-01, 4.78565216e-01,
         3.57228369e-01, 4.27646756e-01, 4.49436426e-01, 3.76300752e-01,
         8.98665786e-01, 4.26868498e-01, 8.45623791e-01, 8.62723172e-01,
         5.63383460e-01, 7.69018531e-01, 1.45424873e-01, 4.35953587e-01,
         5.78069091e-02, 1.32311657e-01, 1.94990233e-01, 6.70868218e-01],
        [1.41025558e-01, 3.47345658e-02, 9.23168898e-01, 7.20130801e-01,
         6.20390512e-02, 3.17977548e-01, 6.22186996e-03, 9.60399806e-01,
         3.39567065e-01, 8.14817131e-01, 7.77464211e-01, 9.20778155e-01,
         1.76566437e-01, 9.95339811e-01, 7.48177528e-01, 5.87782040e-02,
         4.09987062e-01, 9.47237164e-02, 4.15725768e-01, 3.31383824e-01,
         9.47684646e-01, 7.50031888e-01, 5.08836329e-01, 8.09577405e-01,
         7.72107959e-01, 4.09878463e-01, 5.0782454

In [10]:
# 2 resources, 5 features (normalized demand and dummy encoded status), horizon of 28
# different bounds for each dimension...
s8 = spaces.Box(
    low=0,
    high=1,
    shape=[1, 5, 5]
)
print(s8)
s8.sample()

Box(1, 5, 5)


array([[[0.21649833, 0.5500118 , 0.32091758, 0.60365415, 0.52752703],
        [0.41147652, 0.5306478 , 0.1725303 , 0.3085679 , 0.9879016 ],
        [0.03753944, 0.20297773, 0.38391533, 0.17784888, 0.21896377],
        [0.7947827 , 0.51797   , 0.21424547, 0.56023777, 0.47918513],
        [0.4994922 , 0.25551966, 0.63966227, 0.21274312, 0.67171067]]],
      dtype=float32)

In [11]:
low = np.array([[[0], [0], [0], [0], [0]]])
print('LOW\n', low.shape, '\n', low)
high = np.array([[255], [1], [1], [1], [1]])
print('\nHIGH\n', high.shape, '\n', high)

LOW
 (1, 5, 1) 
 [[[0]
  [0]
  [0]
  [0]
  [0]]]

HIGH
 (5, 1) 
 [[255]
 [  1]
 [  1]
 [  1]
 [  1]]


### Hard-coded observation space for shape (1, 5, 5)

In [12]:
low = np.array([[[0, 0, 0 , 0, 0],
        [0   , 0 , 0, 0 , 0],
        [0, 0 , 0, 0, 0],
        [0 , 0, 0 , 0, 0],
        [0 , 0 , 0, 0, 0]]],
      dtype=np.uint8)
print('LOW\n', low.shape, '\n', low)
high = np.array([255, 1, 1, 1, 1])
high = np.array([[[255, 255, 255 , 255, 255],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]]],
      dtype=np.uint8)
print('\nHIGH\n', high.shape, '\n', high)

LOW
 (1, 5, 5) 
 [[[0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]]]

HIGH
 (1, 5, 5) 
 [[[255 255 255 255 255]
  [  1   1   1   1   1]
  [  1   1   1   1   1]
  [  1   1   1   1   1]
  [  1   1   1   1   1]]]


In [13]:
# 2 resources, 5 features (normalized demand and dummy encoded status), horizon of 28
# different bounds for each dimension...
s9 = spaces.Box(
    low=low,
    high=high,
    shape=[1, 5,5],
    dtype=np.uint8
)
print(s9)
s9.sample()

Box(1, 5, 5)


array([[[161,  77, 188, 107, 221],
        [  0,   1,   0,   0,   1],
        [  0,   0,   0,   0,   1],
        [  1,   0,   1,   0,   1],
        [  1,   0,   0,   1,   0]]], dtype=uint8)

### Generated observation space highs for shape (Resources, Timeframe, Features)
The below logic made its way to `_generate_obs_space_HL()` in `rampup-v1`.

In [14]:
fleet_size, horizon, features = 1, 8, 6
bound_hl = 'high'

if bound_hl == 'low':
    bound = 0
else:
    bound = 1

obs_hl = [[]] * fleet_size
l = [[]] * features
for i in range(fleet_size):

    for j in range(features):
        # only the first feature goes up to 255
        if j == 0 and bound_hl == 'high':
            bound = 255
        else:
            bound = 1
        l[j] = [bound] * horizon
    obs_hl[i] = l

np.array(obs_hl, dtype=np.uint8)

array([[[255, 255, 255, 255, 255, 255, 255, 255],
        [  1,   1,   1,   1,   1,   1,   1,   1],
        [  1,   1,   1,   1,   1,   1,   1,   1],
        [  1,   1,   1,   1,   1,   1,   1,   1],
        [  1,   1,   1,   1,   1,   1,   1,   1],
        [  1,   1,   1,   1,   1,   1,   1,   1]]], dtype=uint8)

In [15]:
fleet_size, horizon, features = 1, 8, 6
bound_hl = 'low'

if bound_hl == 'low':
    bound = 0
else:
    bound = 1

obs_hl = [[]] * fleet_size
l = [[]] * features
for i in range(fleet_size):

    for j in range(features):
        # only the first feature goes up to 255
        if j == 0 and bound_hl == 'high':
            bound = 255
        elif bound_hl == 'high':
            bound = 1
        l[j] = [bound] * horizon
    obs_hl[i] = l

np.array(obs_hl, dtype=np.uint8)

array([[[0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0]]], dtype=uint8)